### ISSUE TITLE
为什么不是提供Debian server和Ubuntu desktop

### ISSUE THREAD

**Issue by illuspas** [radxa/debos-radxa#34]

**Comment by dominch** [comment]
I talked about this about year ago #9 
Yes, still no debian cli version :/

**Comment by RadxaYuntian** [comment]
This is because currently the profiles (distro + flavor) is actually manually created. This was a major pain point for us to add additional combinations, or to upgrade base system. As such we are stuck with the past decision.

In the future we will create system images with a [new tool](https://github.com/radxa-repo/rbuild) that can dynamically build images without hard coded config files. We plan to support Debian KDE desktop and CLI version with this new tool to reduce the support variants, while provide Ubuntu images of the same flavor as-is for people with hard OS requirement.

**Comment by RadxaStephen** [comment]
Hi, you can find ROCK 5B Debian11 server image here. https://github.com/radxa-build/rock-5b/releases

Like https://github.com/radxa-build/rock-5b/releases/download/20221125-1014/rock-5b_debian_bullseye_cli.img.xz

Basic information:

* user/password: radxa/radxa

**Comment by RadxaYuntian** [comment]
Please be aware the [release](https://github.com/radxa-build/rock-5b/releases/20221125-1014/) is labelled as pre-release. We do not recommend it being used for production workflow.
